[workspace]
[package]
name = "zktls-sp1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
zktls-att-verification = { git = "https://github.com/primus-labs/zktls-att-verification.git", branch = "main" }

sp1-zkvm = "4.0.0-rc.10"

[patch.crates-io]
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-4.1.0" }
ecdsa-core = { git = "https://github.com/sp1-patches/signatures", package = "ecdsa", tag = "ecdsa-v0.16.9-patch-v3.3.0" }

[features]
risc0 = []
sp1 = []
